Project/urls.py
from django.contrib import admin
from django.urls import path, include
from puc_student.views import login_page, student_list, student_create, student_edit, student_delete, search_students

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_page, name='login'),
    path('student/list/', student_list, name='student_list'),
    path('student/create/', student_create, name='student_create'),
    path('student/edit/<str:matricula>/', student_edit, name='student_edit'),
    path('student/delete/<str:matricula>/', student_delete, name='student_delete'),
    path('search/', search_students, name='search_students'),
]

puc_student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_page, name='login'),
    path('create/', views.student_create, name='student_create'),
    path('edit/<str:matricula>/', views.student_edit, name='student_edit'),
    path('delete/<str:matricula>/', views.student_delete, name='student_delete'),
]

puc_student/models.py
from django.db import models


class Student(models.Model):
    matricula = models.CharField(max_length=20, unique=True)
    nome = models.CharField(max_length=100, default='')
    data_nascimento = models.DateField()
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    data_ingresso = models.DateField()

    def __str__(self):
        return self.matricula

puc_student/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['matricula', 'nome', 'data_nascimento', 'email', 'telefone', 'data_ingresso']
        error_messages = {
            'matricula': {
                'unique': "Já existe um aluno com esta matrícula. Por favor, insira uma matrícula diferente."
            }
        }

puc_student/views.py
import logging
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .models import Student
from .forms import StudentForm

logger = logging.getLogger(__name__)


def login_page(request):
    # Usuários e senhas mockados
    usuarios = ['admin', 'luis', 'professor']
    senhas = ['123', '123456', '12345678']

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        logger.info(f"Tentativa de login com usuário: {username} e senha: {password}")

        if username in usuarios:
            index = usuarios.index(username)
            logger.debug(f"Usuário encontrado na lista de usuários: {username}")

            if password == senhas[index]:
                logger.debug(f"Senha correta para o usuário: {username}")
                user = authenticate(request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    logger.info(f"Usuário {username} autenticado com sucesso")
                    return redirect('student_list')
                else:
                    logger.warning(f"Autenticação falhou para o usuário {username}")
                    error_message = "Usuário ou senha incorretos. Tente novamente."
            else:
                logger.warning(f"Senha incorreta para o usuário: {username}")
                error_message = "Usuário ou senha incorretos. Tente novamente."
        else:
            logger.warning(f"Usuário não encontrado na lista de usuários: {username}")
            error_message = "Usuário ou senha incorretos. Tente novamente."

        return render(request, 'login.html', {'error_message': error_message})

    else:
        return render(request, 'login.html')


def student_list(request):
    students = Student.objects.all()
    return render(request, 'student-list.html', {'students': students})


def student_create(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('student_list')
    else:
        form = StudentForm()
    return render(request, 'student-create.html', {'form': form})


def student_edit(request, matricula):
    student = get_object_or_404(Student, matricula=matricula)
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student_list')
    else:
        form = StudentForm(instance=student)
    return render(request, 'student-edit.html', {'form': form, 'student': student})


def student_delete(request, matricula):
    student = get_object_or_404(Student, matricula=matricula)
    if request.method == 'POST':
        student.delete()
        return redirect('student_list')
    return render(request, 'student-delete.html', {'student': student})

def search_students(request):
    matricula = request.GET.get('matricula', '')
    if matricula:
        students = Student.objects.filter(matricula__icontains=matricula)
    else:
        students = Student.objects.all()
    return render(request, 'student-list.html', {'students': students})

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .login-container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .login-container h2 {
            margin-bottom: 30px;
            text-align: center;
            color: #ffffff;
        }

        .login-container input[type="text"],
        .login-container input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #999999;
            border-radius: 5px;
            box-sizing: border-box;
            background-color: #333333;
            color: #ffffff;
        }

        .login-container input[type="text"]::placeholder,
        .login-container input[type="password"]::placeholder {
            color: #cccccc;
        }

        .login-container button {
            width: 100%;
            padding: 10px;
            background-color: #1a1a1a;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .login-container button:hover {
            background-color: #000000;
        }

        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="login-container">
    <h2>Login</h2>
    <form id="login-form">
        <label>
            <input type="text" id="username" placeholder="Usuário">
        </label>
        <label>
            <input type="password" id="password" placeholder="Senha">
        </label>
        <button type="submit">Entrar</button>
        <p id="error-message" class="error-message"></p>
    </form>
</div>

<script>
    document.getElementById('login-form').addEventListener('submit', function (event) {
        event.preventDefault();

        var username = document.getElementById('username').value;
        var password = document.getElementById('password').value;

        var mockUsers = {
            'admin': '123',
            'luis': '123456',
            'professor': '123456789'
        };

        if (mockUsers.hasOwnProperty(username) && mockUsers[username] === password) {
            alert('Login bem-sucedido!');
            window.location.href = 'student/list';
        } else {
            alert('Usuário ou senha inválidos');
        }
    });
</script>
</body>
</html>

templates/student-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Aluno</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            color: #ffffff;
            width: 700px;
        }

        h2 {
            margin-bottom: 30px;
            text-align: center;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #999999;
            border-radius: 5px;
            box-sizing: border-box;
            background-color: #333333;
            color: #ffffff;
        }

        input[type="text"]::placeholder,
        input[type="email"]::placeholder,
        input[type="password"]::placeholder {
            color: #cccccc;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #1a1a1a;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        button:hover {
            background-color: #000000;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Criar Aluno</h2>
    <form action="{% url 'student_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
        <button onclick="window.history.back();" type="button">Cancelar</button>
    </form>
</div>
<script>
    document.getElementById('id_data_nascimento').addEventListener('input', function (e) {
        var value = e.target.value;
        if (value.length === 2 || value.length === 5) {
            e.target.value += '/';
        }
    });
    document.getElementById('id_data_ingresso').addEventListener('input', function (e) {
        var value = e.target.value;
        if (value.length === 2 || value.length === 5) {
            e.target.value += '/';
        }
    });
</script>

</body>
</html>

templates/student-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excluir Aluno</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            color: #ffffff;
        }

        h2 {
            margin-bottom: 30px;
            text-align: center;
        }

        p {
            margin-bottom: 20px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #1a1a1a;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-bottom: 10px;
        }

        button:hover {
            background-color: #000000;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Excluir aluno</h2>
    <p>Tem certeza que deseja excluir o aluno "{{ student.nome }}" com a matrícula "{{ student.matricula }}"?</p>
    <form action="{% url 'student_delete' student.matricula %}" method="post">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
        <button onclick="window.history.back();" type="button">Cancelar</button>
    </form>
</div>
</body>
</html>

templates/student-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Aluno</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            color: #ffffff;
            width: 700px;
        }

        h2 {
            margin-bottom: 30px;
            text-align: center;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #999999;
            border-radius: 5px;
            box-sizing: border-box;
            background-color: #333333;
            color: #ffffff;
        }

        input[type="text"]::placeholder,
        input[type="password"]::placeholder {
            color: #cccccc;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #1a1a1a;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        button:hover {
            background-color: #000000;
        }

        #id_matricula,
        #id_data_ingresso {
            background-color: #555;
            color: #ccc;
            cursor: not-allowed;
            pointer-events: none;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Editar Aluno</h2>
    <form action="{% url 'student_edit' student.matricula %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
        <button onclick="window.history.back();" type="button">Cancelar</button>
    </form>
</div>

<script>
</script>
</body>
</html>

templates/student-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Alunos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            color: #ffffff;
        }

        h2 {
            margin-bottom: 30px;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ffffff;
        }

        th {
            background-color: #1a1a1a;
            color: #ffffff;
        }

        td {
            background-color: #333333;
            color: #ffffff;
        }

        .actions a {
            margin-right: 10px;
            text-decoration: none;
            color: #ffffff;
        }

        .create-button {
            text-align: center;
            margin-top: 20px;
        }

        .create-button a {
            padding: 10px 20px;
            background-color: #1a1a1a;
            color: #ffffff;
            border-radius: 5px;
            text-decoration: none;
        }

        .create-button a:hover {
            background-color: #000;
        }

        .edit-button {
            background-color: #ffbf00;
            padding: 7px;
            border-radius: 5px;
        }

        .delete-button {
            background-color: #ff0000;
            padding: 7px;
            border-radius: 5px;
        }

        .search-container {
            margin-bottom: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .search-container form {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .search-container input[type="text"] {
            padding: 10px;
            width: 300px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-right: 10px;
        }

        .search-container button[type="submit"],
        .search-container button[type="button"] {
            padding: 10px 20px;
            background-color: #1a1a1a;
            color: #ffffff;
            border-radius: 5px;
            border: none;
            cursor: pointer;
            margin-right: 5px; /* Adicionando margem entre os botões */
        }

        .search-container button[type="submit"]:hover,
        .search-container button[type="button"]:hover {
            background-color: #000;
        }
    </style>
</head>
<body>
{% if students %}
    <div class="container">
        <h2>Lista de Alunos</h2>
        <div class="search-container">
            <form action="{% url 'search_students' %}" method="get">
                <input type="text" name="matricula" placeholder="Digite a matrícula...">
                <button type="submit">Pesquisar</button>
                <button type="button" onclick="window.location.href='{% url 'student_list' %}'">Ver Todos</button>
            </form>
        </div>
        <table>
            <thead>
            <tr>
                <th>Matrícula</th>
                <th>Nome</th>
                <th>Data de Nascimento</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Data de Ingresso</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.matricula }}</td>
                    <td>{{ student.nome }}</td>
                    <td>{{ student.data_nascimento }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.telefone }}</td>
                    <td>{{ student.data_ingresso }}</td>
                    <td class="actions">
                        <a href="{% url 'student_edit' student.matricula %}" class="edit-button">Editar</a>
                        <a href="{% url 'student_delete' student.matricula %}" class="delete-button">Excluir</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="create-button">
            <a href="{% url 'student_create' %}">Criar Novo Estudante</a>
        </div>
    </div>
{% else %}
    <div class="container">
        <h2>Lista de Alunos</h2>
        <div class="search-container">
            <form action="{% url 'search_students' %}" method="get">
                <input type="text" name="matricula" placeholder="Digite a matrícula...">
                <button type="submit">Pesquisar</button>
            </form>
        </div>
        <p>Nenhum aluno encontrado com a matrícula fornecida.</p>
    </div>
{% endif %}
</body>
</html>

templates/student-not-found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aluno não encontrado</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #666666;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            color: #ffffff;
        }

        h2 {
            margin-bottom: 30px;
            text-align: center;
        }

        p {
            margin-bottom: 20px;
        }

        .back-link {
            display: block;
            text-align: center;
            color: #ffffff;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Aluno não encontrado</h2>
        <p>O aluno que você está procurando não foi encontrado.</p>
        <a href="{% url 'student_list' %}" class="back-link">Voltar para Lista de Alunos</a>
    </div>
</body>
</html>